/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClassSelection: typeof import('./src/components/ClassSelection.vue')['default']
    ClickableCard: typeof import('./src/components/ClickableCard.vue')['default']
    RaceSelection: typeof import('./src/components/RaceSelection.vue')['default']
  }
}
